// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package idm

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IdmUser struct {
	Uuid           pgtype.UUID
	Username       string
	Password       []byte
	FirstName      string
	LastName       pgtype.Text
	CreatedAt      pgtype.Timestamp
	LastModifiedAt pgtype.Timestamp
	DeletedAt      pgtype.Timestamp
}

type IdmUserEmail struct {
	Uuid      pgtype.UUID
	Email     string
	UserUuid  pgtype.UUID
	CreatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type Training struct {
	Uuid      pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}
