// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package idm

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT uuid, username, password
FROM idm_users
where username = $1
`

type FindUserByUsernameRow struct {
	Uuid     pgtype.UUID
	Username string
	Password []byte
}

func (q *Queries) FindUserByUsername(ctx context.Context, username string) (FindUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, findUserByUsername, username)
	var i FindUserByUsernameRow
	err := row.Scan(&i.Uuid, &i.Username, &i.Password)
	return i, err
}
